const TYPES = {
    READ_STATE: "READ_STATE",
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_ALL_FROM_CART: "DELETE_ALL_FROM_CART",
    DELETE_PRODUCT_FROM_CART: "DELETE_PRODUCT_FROM_CART",
    CALCULATE_TOTAL_PRICE_OF_THE_CART: "CALCULATE_TOTAL_PRICE_OF_THE_CART"
  }
  
  export default TYPES;